#
# Just Warp - By _arsh.io
# I hope you are enjoying using my plugin!
# Check out my Discord server for support and other releases.
# Discord: https://discord.gg/aBqZe3dgxW
#
# These are the effects settings used with-in Just Warp.

Settings:
  Allow-Movements: false
  Particles: true
  Blindness: true
